name: CI
on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '**.md' # Don't run CI on markdown changes.
  pull_request:
    branches: [ 'main', 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/ci
