name: CI
on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '**.md' # Don't run CI on markdown changes.
  pull_request:
    branches: [ 'main', 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format JSON
        run: |
          ./scripts/ci/format-json.sh
      - name: Ensure no formatting changes needed
        run: git diff --exit-code
      - name: Validate JSON schemas
        run: |
          ./scripts/ci/check-json-schemas.sh
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build
        run: go build ./cmd/ingest
      - name: Sanity test
        run: |
          ./ingest -db test.sqlite3 -create -offline -repo launchdarkly/js-core -metadata ./metadata/launchdarkly_js-core.json 
          length=$(sqlite3 -json test.sqlite3 "SELECT * from sdk_repos;" | jq '. | length')
          if [ $length -ne 6 ]; then
            echo "Expected 6 rows in sdk_repos, got $length"
            exit 1
          fi
