name: Publish GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.22'

      - name: Generate HTML pages
        run: make html

      - name: Create gh-pages branch if it doesn't exist
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
            git checkout -
          fi

      - name: Publish to GitHub Pages
        # launchdarkly/gh-actions/actions/publish-pages@publish-pages-v1.0.2
        uses: launchdarkly/gh-actions/actions/publish-pages@f87da03e3413ce472ac621025890774ce725e373
        with:
          docs_path: _site
          github_token: ${{ secrets.GITHUB_TOKEN }}
