name: Run Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      package-api-js-released: ${{ steps.release.outputs['api-js--release_created'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-npm:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      id-token: write
      contents: write
    if: ${{ needs.release-please.outputs.package-api-js-released == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-npm
        with:
          prerelease: true
          dry_run: false
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
