name: Run Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-npm:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - uses: ./.github/actions/ci
      - uses: ./.github/actions/publish-npm
        with:
          prerelease: true
          dry_run: false
          aws_assume_role: ${{ secrets.AWS_ASSUME_ROLE }}
