name: Run Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Whether to run the release in dry-run mode. If so, then the package will not be published.'
        type: boolean
        required: true
      prerelease:
        description: 'Whether this is a prerelease. If so, then the latest tag will not be updated in npm.'
        type: boolean
        required: true

jobs:
  release-please:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      package-api-js-released: ${{ steps.release.outputs['api-js--release_created'] }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-npm:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      id-token: write
      contents: write
    if: ${{ needs.release-please.outputs.package-api-js-released == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - uses: ./.github/actions/publish-npm
        with:
          prerelease: 'false'
          dry_run: 'false'

  manual-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'

      - uses: ./.github/actions/publish-npm
        with:
          prerelease: ${{ inputs.prerelease }}
          dry_run: ${{ inputs.dry_run }}
